### ISSUE TITLE
Replace EmptyDir with PV

### ISSUE THREAD

**Issue by jortel** [fbladilo/tackle-operator#1]
Replace EmptyDir backed volume with PV backed storage in the tackle-hub (controller) deployment.
Basically we need the DB to be persistent across restarts.
5G should be enough.  Let's mount in `/var/cache/tackle` unless you have a better idea.
The `DB_PATH` environment needs to be set to the mounted volume `/var/cache/tackle/hub.db`

**Comment by fbladilo** [comment]
@jortel EmptyDir volume has been replaced with a persistent volume , the following applies : 

* A new PVC is created by operator, PV RWO access mode and size of 5Gi (default) is requested. Operator controlling variables are : hub_api_bucket_volume_size and hub_api_database_volume_claim_name
* The database volume is mounted in the tackle-hub-api pod in /database and DB_PATH env is set to /database/hub.db. Operator controlling variables are : hub_api_database_volume_path and hub_api_database_filename

I chose to use /database instead of /var/cache , since /var/cache nature is for files that are easily re-created or more volatile than /database , this is per FHS standards.

Sample deployment output and PVC : 
```
    Environment:
      NAMESPACE:          konveyor-tackle (v1:metadata.namespace)
      HUB_TLS_ENABLED:    false
      HUB_BASE_URL:       http://tackle-hub-api.konveyor-tackle.svc:8080
      ADDON_SECRET_PATH:  /var/run/secrets/tackle-addon
      DB_PATH:            /database/hub.db
      BUCKET_PATH:        /buckets
      BUCKET_PVC:         tackle-hub-api-bucket-volume-claim
      DB_SEED_PATH:       /seed
    Mounts:
      /buckets from tackle-hub-api-bucket (rw)
      /database from tackle-hub-api-database (rw)
      /seed from tackle-hub-api-seed (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-htfvb (ro)

oc get pvc  |grep database
tackle-hub-api-database-volume-claim        Bound    pvc-f98ec0e9-4c8a-48d9-acd4-b9d3db2c9b3a   5Gi        RWO            gp2            10m
```

**Comment by jortel** [comment]
:+1: for /database instead of /var/cache.

**Comment by jortel** [comment]
Recommend:  s/hub_api/hub/g  The _api suffix isn't valuable or correct.

**Comment by fbladilo** [comment]
@jortel hub_api is the variable prefix scoping everything related to the hub deployment, I can re-name if hub_api does not make sense for this component. See here : https://github.com/fbladilo/tackle-operator/blob/main/roles/tackle/defaults/main.yml#L19

**Comment by jortel** [comment]
@fbladilo as suggested, let's just use `hub` instead of `hub_api`.
